version: '3.7'

services:
  locations:
    networks:
      - backend
    image: rocfnb/locations
    depends_on:
      - db
      - minio1
    ports:
      - 8080:8080
    restart: always
  db:
    networks:
      - backend
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: fnb
      POSTGRES_DB: fnb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  minio1:
    image: minio/minio:RELEASE.2021-03-04T00-53-13Z
    networks:
      backend:
    volumes:
      - object-data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


# postgresql://postgres:$POSTGRESPASSWORD@localhost:5432
volumes:
  db-data:
  object-data:


networks:
  backend:

secrets:
  psql_password:
    file: ./psql_password
  psql_user:
    file: ./psql_user
